---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - aws_region: sa-east-1
    - security_group_name:  aws-kube-sg
  tasks:
  - name: Get facts from the AWS kube environment instances
    ec2_instance_facts:
      region: '{{aws_region}}'
      filters:
        instance.group-name: '{{security_group_name}}'
    register: ec2_instance_facts_result
  - name: Terminate the AWS kube environment instances
    ec2:
      region: '{{aws_region}}'
      state: absent
      instance_ids: '{{instance_ids}}'
    vars:
      instance_ids: "{{ec2_instance_facts_result|json_query('instances[*].instance_id')}}"
    when: ec2_instance_facts_result.instances|length > 0
  - name: Allocate a new elastic IP and associate it with the aws node
    ec2_eip:
      region: '{{aws_region}}'
      ip: '{{item}}'
      state: absent
      release_on_disassociation: yes
    with_items: "{{ec2_instance_facts_result|json_query('instances[*].public_ip_address')}}"
  - name: Update the inventory file
    lineinfile:
      path: ./hosts
      state: absent
      regexp: '^{{item}} ansible_ssh_host=\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$'
    with_items: "{{ec2_instance_facts_result|json_query('instances[*].public_ip_address')}}"
  - name: Delete the AWS kube security group
    ec2_group:
      region: '{{aws_region}}'
      state: absent
      name: '{{security_group_name}}'
    register: ec2_group_result
    retries: 20
    delay: 10
    until: ec2_group_result is succeeded
